<!DOCTYPE html>
<html>
<head>
  <link rel="stylesheet" type="text/css" href="style/all.css" media="all"/>
<meta charset="UTF-8">

<title> <strong>Sophie Smith</strong> </title>
<script type="text/javascript" src="scripts/jquery-3.2.1.js"></script>
<script type="text/javascript" src="scripts/site.js"></script>
</head>

<body>

<h1> Sophie K. Smith </h1>
<?php
include("includes/navigation.php");
?>

<p class= "bio">My name is Sophie Smith and I just graduated with a Communication major from <a href="http://www.cornell.edu/">Cornell University</a> with a concentration in media studies.
  <?php
   include "includes/aside.php";
  ?>

<h2> Classwork </h2>
<div class="bio">
<p>
  My classwork has focused on
  <a href="https://communication.cals.cornell.edu/"> Communication</a> as a social science. Through this lens, I have learned how to conduct qualitative and quantitative research, analyze statistics, and apply results to Communication theories. 
The more practical courses in my major have given me a base of knowledge in academic and informal writing as well as public speaking and visual analysis. 
humans use symbols, verbal and nonverbal, to create meaning and form relationships with other humans in face-to-face or mediated environments
my classes have discussed the effects of media technologies on society and on our daily lives as well as the media content in relation to gender. These courses included visual communication, oral communication, writing, media, persuasion, new media, personal relationships and technology, gender and the media, psych of entertainment, research methods, and understanding the TV drama.
</p>
</div>
<h2> Education </h2>
<figure>
  <img class="rel-dim" alt="headshot" src="images/headshot.jpg"/>
</figure>
<div class="bio">
<p>
 Aside from my classes in Communication, I have sought other educational opportunities at the college level in various fields of study including broadcast journalism, news writing, acting, sociology, psychology, business and french. I have completed coursework at American University, Northwestern University, University of Wisconsin-Madison, New York University, IESEG School of Management in Paris. 

When I studied abroad in Paris, I took classes at an international business school called <a href="https://www.ieseg.fr/">IESEG</a>. I learned a lot about other parts of the world, France, French, management, marketing, communication, negotiation, branding, retail in the epicenter of Europe. I was able to travel within the continent and expand my knowledge of history, art, culture, and style.
</p>
</div>

<h2> Interests </h2>
<div class="bio">
<p class= "bio">
 I’m interested primarily in journalism and entertainment. Specifically, I am fascinated by the pace of broadcast news and the style of print publications including periodicals, women’s magazines, fashion magazines, news magazines, and newspapers. On the entertainment side, I’m interested in film, TV, and theatre production. I’m avid consumer of all three media and would love to work on the creative or business side of any project. 
</p>
</div>
<h2>Experience</h2>
<div class="bio">
<p class= "bio">
 I have had internships in marketing in various fields including a <a href="https://54below.com/"> theatrical management company</a>, <a href="http://www.truviumfinancial.com/"> financial group</a>, and <a href="http://nydis.org/">non profit</a>. Through these positions, I have gained experience in graphic design, social media content creation, and writing and producing video content for a target audience. I have been also completed administrative tasks involving ticket sales, taking minutes for meetings, sending out emails to customer, making copies, and taking staff photos. 
</p>
</div>
<figure>
  <img class="rel-dim" alt="youngalum" src="images/youngalum.jpg"/>
</figure>
<h2> Extracurriculars </h2>
<div class="bio">
<p>
On campus, I was involved in a variety of organizations. At the <a href="http://cornellsun.com/"> Cornell Daily Sun</a>, I worked in the design department for a year before I made senior staff last spring. I continue to desk weekly for layout, but I now I have also taken on a paid production role in ad layout. My sophomore year I served as secretary for the <a href="https://www.cornelldems.com/">Cornell Democrats</a>, recording attendance, taking minutes, creating promotional materials, assisting in voter registration, and campaigning for local democratic candidates. Last year, I was elected to the position of Communications Director for which I managed our three social media accounts(Facebook, Twitter, and Instagram) and promoted our weekly general body meetings and campus-wide events with quarter-cards and online posts. This year, I’m proud to serve as the Vice President for the club where I assist the President with any and all tasks related to event planning, collaboration with other campus groups, and leading discussions on political issues and current events. Finally, I am involved with the Communication department in the College of Agriculture and Life Sciences and have been a member of the <a href="https://communication.cals.cornell.edu/people/student-advisory-board"> Communication Student Advisory Board</a> for all of my time at Cornell. We facilitate connections between the department’s faculty, alumni, graduate students, and undergrads with networking events like Coffee Chats, COMMConnect, Young Alumni Madness, 
I also mentored incoming transfer students to the department and eased their transition to the major by providing advice on classes, extracurriculars, and student life at Cornell. 
selected to participate in NYCOMM, a networking trip sponsored by the Communication department to New York City to meet with recruiters and media professionals in the industry.
</p>
</div>
<figure>
        <img class="rel-dim" alt="chelsea" src="images/chelsea.jpg"/>
</figure>
<h2> Volunteer </h2>
<div class="bio">
<p>
I have volunteer experience domestically and abroad with the elderly, adults with developmental disabilities, and children. 
</p>
</div>
<h2> High School </h2>
<div class="bio">
<p>
In high school, I was extremely involved extracurricularly. By my senior year, I was a co-captain of the Girls Varsity Tennis Team, Managing Editor of our student newspaper, <a href="http://ihspawprint.com/"> The Paw Print</a>, President of our school’s chapter of <a href="https://www.glamourgals.org/"> Glamour Gals</a>, a community service club that goes to our local nursing home to socialize with and paint the nails of elderly women, President of Irvington Student Tutors, in which I connected high-achieving high school students with elementary and middle school students who needed tutoring or homework help in various subjects for community service, an actor in 7 school plays and musicals, in chorus and chorale. I took voice lessons, 8 AP classes, and graduated with high honors. I was awarded a silver medal on the National Latin Exam for two years, inducted into the Society Honoraire de Francais, and received an award for over 120 hours of community service. Over my summers, I volunteered in Costa Rica through the organization
<a href="https://www.globalworkstravel.com/adventures/costa-rica-language-leadership/"> Global Works</a> for three weeks, attended the <a href="https://www.nslcleaders.org/youth-leadership-programs/journalism-film-media-arts/"> National Student Leadership Conference</a> in Washington D.C. in the Journalism and Mass Communication sector, and participated in the <a href="http://sps.northwestern.edu/program-areas/summer/high-school-programs/college-preparation-program/"> College Prep Program</a> at Northwestern University for 6 weeks. 
</p>
</div>


<?php
include("includes/footer.php");
?>
</body>
</html>
